#!/bin/bash
# SEPOLIA TESTNET SETUP GUIDE

echo "=========================================="
echo "Sepolia Testnet Setup Instructions"
echo "=========================================="
echo ""

echo "STEP 1: Get Sepolia RPC URL"
echo "----------------------------"
echo "Option A - Infura (Recommended):"
echo "  1. Go to https://www.infura.io/register"
echo "  2. Create account and log in"
echo "  3. Create new project (choose 'Ethereum' as network)"
echo "  4. Copy your Sepolia RPC URL from the project dashboard"
echo "  5. It looks like: https://sepolia.infura.io/v3/YOUR_API_KEY"
echo ""
echo "Option B - Alchemy:"
echo "  1. Go to https://www.alchemy.com"
echo "  2. Create account and log in"
echo "  3. Create new app (choose 'Sepolia' network)"
echo "  4. Copy HTTPS URL"
echo "  5. It looks like: https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY"
echo ""

echo "STEP 2: Get Your Private Key"
echo "-----------------------------"
echo "  1. Open MetaMask wallet"
echo "  2. Go to: Account Details → Export Private Key"
echo "  3. Copy your private key (WITHOUT the 0x prefix)"
echo "  ⚠️  WARNING: NEVER share this key publicly!"
echo ""

echo "STEP 3: Create .env File"
echo "------------------------"
echo "  1. Copy .env.example to .env:"
echo "     cp .env.example .env"
echo "  2. Edit .env and fill in:"
echo "     PRIVATE_KEY=your_private_key_without_0x"
echo "     SEPOLIA_RPC_URL=your_infura_or_alchemy_url"
echo "  3. Save and close"
echo ""

echo "STEP 4: Get Sepolia Test ETH"
echo "----------------------------"
echo "  1. Go to https://www.infura.io/faucet/sepolia"
echo "  2. Enter your MetaMask wallet address"
echo "  3. Request test ETH (you get 0.05 ETH)"
echo "  4. Wait 1-2 minutes for it to arrive"
echo ""

echo "STEP 5: Deploy to Sepolia"
echo "------------------------"
echo "  Run: truffle migrate --network sepolia"
echo "  This will:"
echo "  - Use your private key to sign transactions"
echo "  - Send transactions to Sepolia via RPC"
echo "  - Cost real (test) ETH for gas"
echo ""

echo "STEP 6: Run Tests on Sepolia"
echo "----------------------------"
echo "  Run: truffle test --network sepolia"
echo "  ⚠️  This will:"
echo "  - Send REAL transactions to testnet"
echo "  - Cost testnet ETH for each test"
echo "  - Take ~15-20 seconds per test (vs instant locally)"
echo "  - NOT recommended for frequent testing"
echo ""

echo "STEP 7: View on Etherscan"
echo "------------------------"
echo "  1. Go to https://sepolia.etherscan.io"
echo "  2. Search for your contract address or wallet"
echo "  3. View all transactions and events"
echo ""

echo "=========================================="
echo "Setup complete! Run deploy command above."
echo "=========================================="
